export const posts = [
    {
        "id": 2,
        "title": "it's full circle babe",
        "quote": "Lucky Again",
        "date": "February 15, 2024",
        "paragraphs": [
            "“I think that in the discovery of the world around us, we unearth the ability to truly discover ourselves, and I not only want to discover who I am but who I want to be,” <br>-quote by Maggie Moseley in her study abroad purpose statement.",
            "Yes, I quoted myself (I have no idea how self-plagiarism works but I assure you I have permission from past Maggie to use her words). And yes, it sounds pretty cheesy, but even cheesier still is the fact that I really believe it. Hence why I am in a coffee shop in South Australia trying to learn about the world around me and myself too.",
            "<b>Some quick backstory: </b>",
            "I can’t remember when I first decided that I wanted to study abroad, I just know that it has been a goal of mine for a long time. I do, however, remember when I first got obsessed with the idea of Australia- I was 8 and deeply attached to H<sub>2</sub>O: Just Add Water (it was a phase in all of our lives let's be honest). I think I convinced myself that all I needed to do was move to Australia and I’d become a mermaid. Board a flight, touch down, pop a tail. I can now confirm that is not what happened, but little Maggie can dream on, can't she?",
            "Anyway, little me was obsessed with Australia, and slightly older me was obsessed with studying abroad (perhaps I had spent a few too many years in Wyoming where our population is outnumbered by cows). It seems fitting then that when I began at a University with an acclaimed study abroad program, I would be applying to study in Australia before my first week of classes had even ended. Would you believe me though if I said that's not what happened? It's not. In fact, it took a full semester to even schedule a meeting with a study abroad advisor. Why? Probably, and I’m just guessing here, I was scared and had convinced myself that it would be too hard and would set back the completion of my degree.",
            "Luckily, there were people in my life who brought me to my senses. I met with advisors and finally started the process. But, where did I want to go? Scotland. Yep, I wanted to study in Edinburgh. I think the universe was appalled to hear me say that. What do you mean you want to go to Scotland when you've been saying you wanted to study in Australia for the past decade? Luckily a lack of Nutrition programs in the UK proved to be a blessing in disguise. And, lucky again, a quick Google search (“What countries are best for nutrition and dietetics?” Clever, I know) pointed me in the right direction. From there it took blood, sweat, tears (mainly tears), and a lot of hard work. Now though, I am in a coffee shop in South Australia."

        ]
    },
    {
        "id": 1,
        "title": "One less Wednesday",
        "quote": "I think I can afford to lose a day or two",
        "date": "February 8, 2024",
        "paragraphs": [
            "It takes approximately 22 hours to get from Denver International Airport to Sydney International Airport and an additional 2 hours to get from Sydney in New South Wales to Adelaide in South Australia. And, because of the time difference, if you fly out on a Tuesday, as I did, you won't reach Australia until Thursday. I’ve taken many flights in which I lost or gained an hour, but I’ve never lost an entire day before. It’s a weird concept to grasp. I genuinely thought that it was time travel for a while (and I still have my suspicions). But regardless of whether the flight to Australia should be considered an X-File or not, it was still a profound episode in my life.",
            "Just over two weeks ago I was somewhere over the Pacific Ocean, my AirPods in, music blasting (to cover the sound of people snoring around me), and tears in my eyes. I was so incredibly excited to be embarking on this journey but I was terrified and sad too. I was terrified because waiting for me when we touched down was something completely unknown. And I was sad, sad to say goodbye to the people that had brought me so much joy and had become my home. *Scpiel Alert* Home is something I have struggled with for a few years now. After my parents divorced, and my Dad moved, it was just my mom and me in my childhood house. Staying there brought me comfort and stability, though everything else seemed to change, I still had my home, even if it wasn't quite the same anymore. But when I moved away to college my mom needed to sell it so that she could move out too. It was, and still is, a hard pill to swallow. Over holiday breaks most others go home, back to their childhood bedrooms and the towns that raised them. It hurt to go back home and not actually have a ‘home’ there. It was strange to visit my hometown and feel like that's all it was- a visit. Combine that confusion with the fact that I felt horribly uncomfortable in my college town and you get a year and a half of disheartening limbo. So when that began to feel too much like a stubbing-your-toe-centric-Groundhog Day and I’d had enough, I decided to change things up.",
            "Luckily it was already a goal of mine to study abroad so that's what I did. But when it came time to leave, to actually say goodbye, that’s when I realized that while I hadn’t found a place that felt like home again, I’d found people that did- the perfect epiphany to have as you are packing to move to the other side of the planet. Like that's a bit cruel. So yeah, I cried on the plane about it, whatever. And though I’ve cried multiple times since I’ve been here, I also catch myself smiling simply walking down the street (as someone with chronic RBF this is a pretty big deal, don't get it twisted).",
            "I’m currently living out one of my biggest dreams and I couldn’t be happier. I still get sad every once in a while, I obviously still have moments of terror and uncertainty, and I know that I will continue to have these moments the entire time I am here. But I am learning to embrace these challenges, to learn and grow from them, and to emerge from them with more confidence in myself. And I’ve already had quite a few challenges since rolling my suitcase off that plane. Like that time I got completely lost on campus (Google Maps is not to be trusted) trying to get my ID card. Or that time I had to go to an urgent care clinic (I’ve not even been here for a month) and fell into a wall because of some questionable treatment practices. I stumbled my way out of that office with an irrigation-of-the-ear-canal-induced dizzy spell, but I still made it to my apartment- and there’s a life lesson in that.",
            "Naturally, there were a lot of things I had to say a temporary goodbye to in order to be here now: my friends, driving on the right side of the road, my parents, my American SIM card, the rest of my family, the imperial system, my apartment in Laramie, oh yeah, and an entire Wednesday. But, I think I can afford to lose a day or two as long as I promise myself that I will not waste any more unnecessary time being scared (some time being scared is however still necessary).",
            "So, this is the first installment in my chronicles abroad (and a blog that I told a scholarship I would do if they gave me money, which they did so here we are). Here’s the plan for context, not so you can hold me to it- I’m a stressed college student in a foreign country give me a break. My posts will be bimonthly (maybe) and will cover everything from each step of the study abroad process (complete with my personal experiences and highly regarded advice for prospective exchange students), to my adventures while abroad and everything I am learning through this journey. This is my solo journey but I’m kind enough to let you guys join me once in a while, you're welcome. So, here's to many more Wednesdays to come (and also the other days too)."

        ]
    }
]